export const LANGUAGE_NAMES: Record<string, string> = {
	"en-US": "English",
	"en-GB": "English",
	"es-ES": "Spanish",
	"es-US": "Spanish",
	"fr-FR": "French",
	"de-DE": "German",
	"it-IT": "Italian",
	"pt-BR": "Portuguese",
	"pt-PT": "Portuguese",
	"nl-NL": "Dutch",
	"pl-PL": "Polish",
	"ru-RU": "Russian",
	"tr-TR": "Turkish",
	"sv-SE": "Swedish",
	"id-ID": "Indonesian",
	"vi-VN": "Vietnamese",
	"th-TH": "Thai",
	"hi-IN": "Hindi",
	"ar-SA": "Arabic",
	"zh-CN": "Mandarin Chinese",
	"ja-JP": "Japanese",
	"ko-KR": "Korean",
	en: "English",
	es: "Spanish",
	fr: "French",
	de: "German",
	it: "Italian",
	pt: "Portuguese",
	nl: "Dutch",
	pl: "Polish",
	ru: "Russian",
	tr: "Turkish",
	sv: "Swedish",
	id: "Indonesian",
	vi: "Vietnamese",
	th: "Thai",
	hi: "Hindi",
	ar: "Arabic",
	zh: "Mandarin Chinese",
	ja: "Japanese",
	ko: "Korean",
	sw: "Swahili",
	tw: "Twi",
	ee: "Ewe",
	ha: "Hausa",
	yo: "Yoruba",
	am: "Amharic",
};

export const buildTranslationPrompt = (sourceLang: string, targetLang: string) => {
	const sourceName = LANGUAGE_NAMES[sourceLang] ?? sourceLang;
	const targetName = LANGUAGE_NAMES[targetLang] ?? targetLang;
	return `You are a translation engine. Translate the user's message from ${sourceName} to ${targetName}. Output ONLY the translated text. No quotes, no preamble, no explanations, no alternatives. Preserve tone and punctuation. If the text is already in ${targetName}, return it unchanged.`;
};
